name: opticscan
description: "Optic Scan Mobile App"

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.2

# --------------- PACKAGES----------------

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #HTTP
  dio: ^5.8.0+1
  # State manajemen
  get: ^4.7.2
  lucide_icons: ^0.257.0
  camera: ^0.11.1
  image_picker: ^1.1.2
  # Formatter
  intl: ^0.20.2
  #storage key and jwt
  shared_preferences: ^2.5.2
  jwt_decoder: ^2.0.1
# --------------- PACKAGES END -----------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/

  # ------------ LOCAL FONTS --------
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/cabin_font.ttf
    - family: Greycliff
      fonts:
        - asset: assets/fonts/greycliff_font.otf
